/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_fork_MainActivity */

#ifndef _Included_cn_itcast_fork_MainActivity
#define _Included_cn_itcast_fork_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_fork_MainActivity
 * Method:    callC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_itcast_fork_MainActivity_callC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
