/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_cplusplus_MainActivity */

#ifndef _Included_cn_itcast_cplusplus_MainActivity
#define _Included_cn_itcast_cplusplus_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_cplusplus_MainActivity
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itcast_cplusplus_MainActivity_helloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
